In [6]:
# Importing libraries
import pandas as pd
import numpy as np

# Read csv file into a pandas dataframe
df = pd.read_csv("31084524_dirty_data.csv")

# Take a look at the first few rows
df.head()

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD196541,ID1283628999,2019-09-17,Thompson,"[('iAssist Line', 2), ('iStream', 2), ('Univer...",11650,108.90,-37.799723,144.955257,5,18513.79,Spring,True,1.6115,this was a mother's day gift from my son. i ha...,True
1,ORD288326,ID1479905345,2019-05-25,Nickolson,"[('Toshika 750', 2), ('iStream', 1), ('Lucent ...",11250,80.15,-37.820750,144.957444,5,10767.65,Autumn,False,1.0913,clear music,True
2,ORD118948,ID0575386501,2019-07-28,Nickolson,"[('Thunder line', 2), ('Alcon 10', 2), ('Toshi...",26880,80.28,-37.819935,144.984444,5,25616.28,Winter,True,1.3181,four stars good phone but not what i needed,True
3,ORD351033,ID0030287874,2019-07-12,Bakers,"[('Toshika 750', 1), ('Universe Note', 1), ('A...",25670,85.83,-37.823339,145.014406,10,23188.83,Winter,True,2.2470,great product!! love it it's perfect! love it ...,True
4,ORD198886,ID5563404259,2019-04-13,Bakers,"[('iStream', 2), ('Toshika 750', 1), ('Lucent ...",13390,53.60,145.008947,-37.816534,5,12774.10,Autumn,False,1.4087,"not worth anything garbage processing speed, c...",False

In [7]:
df['shopping_cart'] =  df['shopping_cart'].apply(lambda x: x.replace('[(','').replace(']',''))

In [8]:
df

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD196541,ID1283628999,2019-09-17,Thompson,"'iAssist Line', 2), ('iStream', 2), ('Universe...",11650,108.90,-37.799723,144.955257,5,18513.79,Spring,True,1.6115,this was a mother's day gift from my son. i ha...,True
1,ORD288326,ID1479905345,2019-05-25,Nickolson,"'Toshika 750', 2), ('iStream', 1), ('Lucent 33...",11250,80.15,-37.820750,144.957444,5,10767.65,Autumn,False,1.0913,clear music,True
2,ORD118948,ID0575386501,2019-07-28,Nickolson,"'Thunder line', 2), ('Alcon 10', 2), ('Toshika...",26880,80.28,-37.819935,144.984444,5,25616.28,Winter,True,1.3181,four stars good phone but not what i needed,True
3,ORD351033,ID0030287874,2019-07-12,Bakers,"'Toshika 750', 1), ('Universe Note', 1), ('Alc...",25670,85.83,-37.823339,145.014406,10,23188.83,Winter,True,2.2470,great product!! love it it's perfect! love it ...,True
4,ORD198886,ID5563404259,2019-04-13,Bakers,"'iStream', 2), ('Toshika 750', 1), ('Lucent 33...",13390,53.60,145.008947,-37.816534,5,12774.10,Autumn,False,1.4087,"not worth anything garbage processing speed, c...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD496551,ID0579994804,2019-02-14,Thompson,"'Thunder line', 1), ('Lucent 330S', 1)",8490,97.96,-37.804138,144.938421,0,8587.96,Summer,True,1.2170,a good phone the home button did act up for a ...,True
496,ORD465466,ID6197211189,2019-10-13,Thompson,"'Thunder line', 2), ('Lucent 330S', 2), ('pear...",13130,109.42,-37.814965,144.927566,5,12582.92,Spring,False,1.7340,great buy phone came in generic packaging. wor...,True
497,ORD206695,ID0778942366,2019-13-01,Bakers,"'iAssist Line', 1), ('Lucent 330S', 1)",3455,86.42,-37.814161,145.014446,0,3541.42,Summer,True,1.7522,"its junk it quit calling out after three week,...",False
498,ORD375794,ID0306067099,2019-10-15,Nickolson,"'Candle Inferno', 1), ('iAssist Line', 1), ('i...",5135,78.25,-37.808812,144.973922,5,4956.50,Spring,False,1.1549,nice.... except for the data problem. this pro...,True
499,ORD265535,ID0126934555,2019-06-23,Nickolson,"'Universe Note', 2), ('iAssist Line', 1), ('Ca...",13915,64.62,-37.816211,144.966471,5,13283.87,Summer,False,0.3792,five stars good stuff and fast delivery,True

In [9]:
df['shopping_cart'] =  df['shopping_cart'].apply(lambda x: x.replace('(','').replace(')',''))

In [12]:
df

,order_id,customer_id,date,nearest_warehouse,shopping_cart,order_price,delivery_charges,customer_lat,customer_long,coupon_discount,order_total,season,is_expedited_delivery,distance_to_nearest_warehouse,latest_customer_review,is_happy_customer
0,ORD196541,ID1283628999,2019-09-17,Thompson,"'iAssist Line', 2, 'iStream', 2, 'Universe Not...",11650,108.90,-37.799723,144.955257,5,18513.79,Spring,True,1.6115,this was a mother's day gift from my son. i ha...,True
1,ORD288326,ID1479905345,2019-05-25,Nickolson,"'Toshika 750', 2, 'iStream', 1, 'Lucent 330S', 2",11250,80.15,-37.820750,144.957444,5,10767.65,Autumn,False,1.0913,clear music,True
2,ORD118948,ID0575386501,2019-07-28,Nickolson,"'Thunder line', 2, 'Alcon 10', 2, 'Toshika 750...",26880,80.28,-37.819935,144.984444,5,25616.28,Winter,True,1.3181,four stars good phone but not what i needed,True
3,ORD351033,ID0030287874,2019-07-12,Bakers,"'Toshika 750', 1, 'Universe Note', 1, 'Alcon 1...",25670,85.83,-37.823339,145.014406,10,23188.83,Winter,True,2.2470,great product!! love it it's perfect! love it ...,True
4,ORD198886,ID5563404259,2019-04-13,Bakers,"'iStream', 2, 'Toshika 750', 1, 'Lucent 330S',...",13390,53.60,145.008947,-37.816534,5,12774.10,Autumn,False,1.4087,"not worth anything garbage processing speed, c...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD496551,ID0579994804,2019-02-14,Thompson,"'Thunder line', 1, 'Lucent 330S', 1",8490,97.96,-37.804138,144.938421,0,8587.96,Summer,True,1.2170,a good phone the home button did act up for a ...,True
496,ORD465466,ID6197211189,2019-10-13,Thompson,"'Thunder line', 2, 'Lucent 330S', 2, 'pearTV', 1",13130,109.42,-37.814965,144.927566,5,12582.92,Spring,False,1.7340,great buy phone came in generic packaging. wor...,True
497,ORD206695,ID0778942366,2019-13-01,Bakers,"'iAssist Line', 1, 'Lucent 330S', 1",3455,86.42,-37.814161,145.014446,0,3541.42,Summer,True,1.7522,"its junk it quit calling out after three week,...",False
498,ORD375794,ID0306067099,2019-10-15,Nickolson,"'Candle Inferno', 1, 'iAssist Line', 1, 'iStre...",5135,78.25,-37.808812,144.973922,5,4956.50,Spring,False,1.1549,nice.... except for the data problem. this pro...,True
499,ORD265535,ID0126934555,2019-06-23,Nickolson,"'Universe Note', 2, 'iAssist Line', 1, 'Candle...",13915,64.62,-37.816211,144.966471,5,13283.87,Summer,False,0.3792,five stars good stuff and fast delivery,True

In [13]:
df['shopping_cart'].head(2)

0    'iAssist Line', 2, 'iStream', 2, 'Universe Not...
1     'Toshika 750', 2, 'iStream', 1, 'Lucent 330S', 2
Name: shopping_cart, dtype: object